'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle, ChevronLeft, ChevronRight, Download, RefreshCw, Search, ShieldAlert, XCircle } from 'lucide-react';
import AdminNavbar from '@/components/admin/AdminNavbar';
import AdminSideNav from '@/components/admin/AdminSideNav';
const ROLE_LABELS={admin:'System Admin',site_clerk:'Site Clerk',hr:'HR Manager',accountant:'Accountant',ceo:'CEO / Executive'};
const csvCell=(v)=>`"${String(v??'').replaceAll('"','""')}"`;
export default function SecurityAuditLogsPage(){
 const[logs,setLogs]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[module,setModule]=useState('ALL'),[currentPage,setCurrentPage]=useState(1); const perPage=10;
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/audit-logs?limit=500',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Could not load audit logs.');setLogs(j.data||[]);}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const modules=useMemo(()=>[...new Set(logs.map(l=>l.module).filter(Boolean))].sort(),[logs]);
 const filtered=useMemo(()=>logs.filter(l=>{const actor=l.actor?`${l.actor.first_name||''} ${l.actor.last_name||''}`.trim():'System';const hay=[actor,l.actor?.email,l.action,l.module,l.entity_type,l.details].filter(Boolean).join(' ').toLowerCase();return hay.includes(search.toLowerCase())&&(status==='ALL'||l.status===status)&&(module==='ALL'||l.module===module)}),[logs,search,status,module]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/perPage)),page=Math.min(currentPage,totalPages),shown=filtered.slice((page-1)*perPage,page*perPage);
 function exportCsv(){const rows=[['Timestamp','Actor','Role','Action','Module','Entity','Status','Details'],...filtered.map(l=>[l.created_at,l.actor?`${l.actor.first_name||''} ${l.actor.last_name||''}`.trim():'System',ROLE_LABELS[l.actor?.role]||l.actor?.role||'System',l.action,l.module,l.entity_type||'',l.status,l.details||''])];const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`security_audit_logs_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="min-h-screen bg-slate-100 text-slate-900 flex flex-col lg:flex-row font-sans"><AdminSideNav/><main className="flex-1 p-4 sm:p-6 lg:p-8 space-y-6 overflow-x-hidden"><AdminNavbar title="Security & Audit Logs"/>
 {error&&<div className="bg-rose-50 border border-rose-200 text-rose-700 rounded-xl p-4 text-xs font-semibold">{error}</div>}
 <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Stat icon={<Activity className="w-5 h-5"/>} label="Audit Events" value={logs.length}/><Stat icon={<CheckCircle className="w-5 h-5"/>} label="Successful Operations" value={logs.filter(l=>l.status==='SUCCESS').length}/><Stat icon={<AlertTriangle className="w-5 h-5"/>} label="Exceptions / Warnings" value={logs.filter(l=>l.status!=='SUCCESS').length}/></div>
 <div className="bg-white p-4 rounded-2xl border border-slate-200 flex flex-col lg:flex-row gap-3 justify-between"><div className="relative w-full lg:max-w-md"><Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setCurrentPage(1)}} placeholder="Search actor, action, module or details..." className="w-full pl-10 pr-4 py-2.5 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-none"/></div><div className="flex flex-wrap gap-2"><select value={status} onChange={e=>{setStatus(e.target.value);setCurrentPage(1)}} className="text-xs border border-slate-200 bg-slate-50 rounded-xl px-3"><option value="ALL">All statuses</option><option value="SUCCESS">Success</option><option value="FAILED">Failed</option><option value="WARNING">Warning</option></select><select value={module} onChange={e=>{setModule(e.target.value);setCurrentPage(1)}} className="text-xs border border-slate-200 bg-slate-50 rounded-xl px-3"><option value="ALL">All modules</option>{modules.map(m=><option key={m} value={m}>{m}</option>)}</select><button onClick={load} disabled={loading} className="p-2.5 border border-slate-200 rounded-xl bg-slate-50"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button><button onClick={exportCsv} disabled={!filtered.length} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-bold disabled:bg-slate-300"><Download className="w-4 h-4"/>Export CSV</button></div></div>
 <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 border-b border-slate-200"><tr>{['TIMESTAMP','ACTOR','ACTION','MODULE','STATUS','DETAILS'].map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={6} className="py-16 text-center text-slate-500">Loading real audit events...</td></tr>:shown.length===0?<tr><td colSpan={6} className="py-16 text-center"><ShieldAlert className="w-8 h-8 text-slate-300 mx-auto mb-2"/><p className="font-semibold text-slate-600">No audit events recorded yet.</p><p className="text-slate-400 mt-1">New governed system actions will appear here automatically.</p></td></tr>:shown.map(l=>{const actor=l.actor?`${l.actor.first_name||''} ${l.actor.last_name||''}`.trim()||l.actor.email:'System';return <tr key={l.id} className="hover:bg-slate-50"><td className="px-5 py-4 whitespace-nowrap text-slate-500">{new Date(l.created_at).toLocaleString()}</td><td className="px-5 py-4"><b>{actor}</b><div className="text-[10px] text-slate-400">{ROLE_LABELS[l.actor?.role]||l.actor?.role||'System'}</div></td><td className="px-5 py-4 font-mono font-semibold">{l.action}</td><td className="px-5 py-4">{l.module}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold ${l.status==='SUCCESS'?'bg-emerald-50 text-emerald-700':l.status==='FAILED'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{l.status==='SUCCESS'?<CheckCircle className="w-3 h-3"/>:<XCircle className="w-3 h-3"/>}{l.status}</span></td><td className="px-5 py-4 text-slate-600 min-w-[260px]">{l.details||'—'}</td></tr>})}</tbody></table></div><div className="px-5 py-3 border-t border-slate-200 bg-slate-50 flex items-center justify-between text-xs text-slate-500"><span>{filtered.length} matching event{filtered.length===1?'':'s'}</span><div className="flex items-center gap-2"><button disabled={page<=1} onClick={()=>setCurrentPage(p=>Math.max(1,p-1))} className="p-1.5 border rounded-lg disabled:opacity-40"><ChevronLeft className="w-4 h-4"/></button><span>Page {page} of {totalPages}</span><button disabled={page>=totalPages} onClick={()=>setCurrentPage(p=>Math.min(totalPages,p+1))} className="p-1.5 border rounded-lg disabled:opacity-40"><ChevronRight className="w-4 h-4"/></button></div></div></div>
 </main></div>}
function Stat({icon,label,value}){return <div className="bg-white p-5 rounded-2xl border border-slate-200 flex items-center gap-4"><div className="p-3 bg-indigo-50 rounded-xl text-indigo-600">{icon}</div><div><p className="text-xs font-semibold text-slate-400">{label}</p><h3 className="text-xl font-bold">{value}</h3></div></div>}
